-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table students (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  index_number                  varchar(255),
  constraint pk_students primary key (id)
);


-- !Downs

-- drop all
drop table if exists students cascade;

